apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Beautiful PHP Web Application with Modern UI, API endpoints, Docker deployment and Jenkins CI/CD
  annotations:
    github.com/project-slug: febinqburst/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: ${{ values.app_name }}-pipeline
spec:
  type: service
  owner: ${{values.owner}}
  lifecycle: experimental
  system: default-system